# Docker Compose reads this file to define:
# - services
# - networks
# - volumes
# - build context
# - environment variables
#❗️❗️❗️注意：要在学校VM环境里把volumes改成/home/luxu/data/wordpress和/home/luxu/data/mariadb
# Volumes are used to keep important data persistent outside containers.
# This means the data can survive even if a container is stopped, removed,
# or recreated.
# In this project:
# - wordpress_data stores the WordPress website files
# - mariadb_data stores the MariaDB database files

# Service startup order: MariaDB -> WordPress -> Nginx
# However, this does not guarantee that MariaDB is fully ready
# when WordPress starts.
# depends_on only controls startup order.
# It does not configure networking or volume sharing.

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # "ports" maps a container port to the host machine,
    # so the service can be accessed from outside Docker.
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    # "expose" makes a port available only to other containers
    # on the same Docker network, not to the host.
    expose:
      - "9000"
    secrets:
      - db_password
      - credentials
      - user_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  user_password:
    file: ../secrets/user_password.txt

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception:
    driver: bridge
