# 开始一个server配置模块，可以把server理解成nginx里的一台"网站服务配置"
# 这一整块都是在告诉nginx: 监听哪个端口，处理哪个域名，用哪个证书，网站根目录在哪里；收到请求后怎么处理

server {
  	#listen to the HTTPS default port (443); when the client end visits port 443 via HTTPS, Nginx receives the demand here
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name luxu.42.fr;

	#To check the main configuration file of Nginx server: docker exec -it (containerName) /bin/bash
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	root /var/www/html;
	index index.php index.html index.htm;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	# After the docker compose network built: nginx receives the demands of the navigator and hand it to php-fpm
	# through 9000 port
	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
